# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_MODEL_GREATLE) += exynos8895-greatlte_eur_open_06.dtb \
	exynos8895-greatlte_eur_open_06.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
