dtb-$(CONFIG_MODEL_GREATLTE) += exynos8895-greatlte_eur_open_00.dtb exynos8895-greatlte_eur_open_01.dtb exynos8895-greatlte_eur_open_02.dtb exynos8895-greatlte_eur_open_06.dtb 

always		:= $(dtb-y)
targets += dtbs
dtbs: $(addprefix $(obj)/, $(DTB_LIST))
